### ISSUE TITLE
swagg-request doesn't prompt for required requestBody

### ISSUE THREAD

**Issue by c308-cnelson** [isamert/swagg.el#1]
It seems like swagg-request will prompt the user for any required parameters, except those listed as required under requestBody

**Comment by c308-cnelson** [comment]
Looking further into this it seems like bodies are not supported with swagg-request. 
"This function does not support requests with bodies.  For that,
see `swagg-request-with-rest-block'."

Could that potentially be an added feature?

**Comment by isamert** [comment]
Definitely, but I wasn't able to come up with a flow that eases up the process. `swagg-request` is not very usable in my opinion, especially if there are lots of parameters and requesting the body with `read-string` did not make sense to me because the body is generally something that you need to edit in a buffer. Anyway I can make it request the requestBody if it's required. If you have alternative idea for requesting the body (other than just using `read-string`), I would like to hear but I hesitate it that it'll be superseded by the `swagg-request-with-rest-block`.

Any reason not to use `swagg-request-with-rest-block`?

**Comment by c308-cnelson** [comment]
Thanks for the reply! The main reason I was looking to use swagg-request
was because it was a little more interactive for quick tests than
swagg-request-with-rest-block, which requires you to kinda "setup" the call
(add org-babel blocks around it with the right header args). I suppose a
potentially better alternative might be to wrap the output block in a src
block and prompt the user to enter the correct args
(verb/restclient/ob-http). Thoughts?

**Comment by isamert** [comment]
You can utilize the `swagg-rest-block-prelude`,
`swagg-rest-block-postlude` variables to wrap them with src block (or
whatever you want) automatically, variable documentations contains
examples.

There is also `swagg-rest-block-org-header-tags`. This is mainly for
using verb without src blocks, if you prefer that way. See the
variable documentation.

Can you check how is it working for you and let me know if there can
be improvements?

**Comment by c308-cnelson** [comment]
Oh I didn't realize that was an option 🤦. That works great! The only thing I noticed is that when the openapi spec has a top level security declaration, the generated rest calls aren't including the required header (when the securityScheme is set to bearer). Thanks for the help btw!

**Comment by isamert** [comment]
Great! I'll close this one and track the other thing you've said in another issue.
